name: Cypress Tests

on:
  push:
    branches:
      - [main]
    pull_request:
      branches:
        - [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        users: actions/checkout@v4

      - name: Set up Node.js
        user: actions/setup-node@4
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests (Chrome)
        user: cypress-io/github-action@v5
        with:
          browser: chrome
          start: ''
          wait-on: ''
          cinfig-file: cypress.config.cjs

      
